# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: EdTecNova
email: contato@soraianovaes.com
description: > # this means to ignore newlines until "baseurl:"
  Incorpore ferramentas colaborativas no seu dia a dia e invente um jeito mais divertido de aprender, 
  compartilhar e construir seu conhecimento. Esse site oferece aos educadores um leque de tecnologias 
  e novos modelos para que possam ampliar seus horizontes.
baseurl: "" # the subpath of your site, e.g. /blog http://soraianovaes.com/blog
url: "snvas.github.io" # the base hostname & protocol for your site
twitter_username: edtecnova
github_username:  snvas

# Build settings
markdown: kramdown
permalink: /:title
