# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: CodeCamp
name: Soraia Novaes
email: contato@soraianovaes.com
description: > # this means to ignore newlines until "baseurl:"
  Incorpore ferramentas colaborativas no seu dia a dia e invente um jeito mais divertido de aprender, 
  compartilhar e construir seu conhecimento. Conheça novas tecnologias, novos modelos e amplie seus horizontes.
baseurl: "" # the subpath of your site, e.g. /blog http://soraianovaes.com/blog
url: "http://codecamp.com.br" # the base hostname & protocol for your site
author: Soraia Novaes
twitter:
  username: edtecnova
github_username:  snvas

# Build settings
markdown: kramdown
permalink: /:title
gems:
  - jekyll-tagging
  - jekyll-feed
  - jekyll-seo-tag

theme: jekyll-material-theme

tag_page_layout: tags  
social:
  name: Soraia Novaes
  links:
    - https://twitter.com/edtecnova
    - https://www.facebook.com/soraianovaes
    - https://www.linkedin.com/in/soraianovaes
    - https://plus.google.com/+SoraiaNovaes
    - https://github.com/snvas
    - http://www.soraianovaes.com


display_footer: inital  #change this to 'none' if you want to hide the footer copyright text

parallax_image_one: assets/images/startup3.jpg # These are the images used for the parallax background
parallax_image_two: assets/images/startup3.jpg

# Settings for the porfolio section

portfolio_heading: Portfolio
portfolio_type: cards #cards or carousel

project_one: "First Project"
project_one_description: Describe your project!
project_one_url: https://github.com/jameshamann/jekyll-material-theme
project_one_icon: location_on # these are from materiailize css, the full collection is here: http://materializecss.com/icons.html

project_two: Second Project
project_two_description: Describe your project!
project_two_url: https://github.com/jameshamann/jekyll-material-theme
project_two_icon: photo_camera


project_three: Third Project
project_three_description: Describe your project!
project_three_url: https://github.com/jameshamann/jekyll-material-theme
project_three_icon: hotel


project_four: Fourth Project
project_four_description: Describe your project!
project_four_url: https://github.com/jameshamann/jekyll-material-theme
project_four_icon: restaurant

# Skill icons from https://konpa.github.io/devicon/

skills:
  - name: bootstrap
  - name: chrome
  - name: css3
  - name: facebook
  - name: git
  - name: github
  - name: gitlab
  - name: google
  - name: html5
  - name: illustrator
  - name: inkscape
  - name: javascript
  - name: moodle
  - name: mysql
  - name: photoshop
  - name: php
  - name: ruby
  - name: trello
  - name: twitter
  - name: wordpress

icon_size: 50 # font-size of icons in px
colored: colored # Leave blank for black and white icons

project_button: Github

github: https://github.com/jameshamann/jekyll-material-theme
medium: https://medium.com

# Google tracking, if both are filled, tag manager will prevail. Set up GA through GTM in that case
tag_manager_id: # This looks something like GTM-XXXXXXX
google_analytics_tracking_id: # This looks something like UA-000000000-0 Head over to https://analytics.google.com/ to setup.

cookie_accept_message: Thanks! # The pop-up dialog that appears after accepting the cookie notice.

syntax_highlighting: true # include the css for syntax highlighting

plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-minifier