# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: CodeCamp
email: contato@soraianovaes.com
description: > # this means to ignore newlines until "baseurl:"
  Incorpore ferramentas colaborativas no seu dia a dia e invente um jeito mais divertido de aprender, 
  compartilhar e construir seu conhecimento. Conheça novas tecnologias e novos modelos e amplie seus horizontes.
baseurl: "" # the subpath of your site, e.g. /blog http://soraianovaes.com/blog
url: "http://codecamp.com.br" # the base hostname & protocol for your site
author: Soraia Novaes
twitter:
  username: edtecnoca
github_username:  snvas

# Build settings
markdown: kramdown
permalink: /:title
gems:
  - jekyll-tagging
  - jekyll-feed
tag_page_layout: tag_page
tag_page_dir: tag  
social:
  name: Soraia Novaes
  links:
    - https://twitter.com/edtecnova
    - https://www.facebook.com/soraianovaes
    - https://www.linkedin.com/in/soraianovaes
    - https://plus.google.com/+SoraiaNovaes
    - https://github.com/snvas
    - http://www.soraianovaes.com